image: node:22

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

variables:
  TARGET_BRANCH: "pages"  # The branch to store static files

build_site:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - out/
  only:
    - tags
    - triggers

deploy_pages:
  stage: deploy
  needs: ["build_site"]
  script:
    - mv out public
    - |
      git config --global user.email "ci-runner@gitlab.com"
      git config --global user.name "GitLab CI"
      if git ls-remote --exit-code --heads origin $TARGET_BRANCH; then
        git checkout $TARGET_BRANCH
      else
        git checkout --orphan $TARGET_BRANCH
      fi
      rm -rf *
      cp -r ../public/* .
      git add .
      git commit -m "Deploy static site for $CI_COMMIT_TAG" || echo "Nothing to commit"
      git push --force "https://${CI_REPOSITORY_URL#https://}" HEAD:$TARGET_BRANCH

  only:
    - tags
    - triggers
