image: node:22

variables:
  NEXT_PUBLIC_GITLAB_PAGES: "1"

stages:
  - build

pages:
  stage: build
  script:
    - echo $NEXT_PUBLIC_GITLAB_PAGES
    - npm ci
    - npm run build
  artifacts:
    paths:
      - out
  only:
    - main
